GET http://localhost:3000/api/bids
Accept: application/json


###
POST http://localhost:3000/api/bids
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdlcnJhbHRAZW1haWwuY29tIiwiaWQiOjAsInVzZXJuYW1lIjoiZ2VycmFsdCIsInJvbGVzIjpbInVzZXIiLCJhZG1pbiJdLCJpYXQiOjE2MzI2NjA2MDZ9.GUKQJiEHHX3C_abjJj3TSxQxxmU8arPz5iaHokjxd4M
Content-Type: application/json

{
  "price": 100,
  "auctionId": 0
}

###
GET http://localhost:3000/api/bids
Accept: application/json

###
GET http://localhost:3000/api/bids?hasWon=true&userId=1
Accept: application/json

###
GET http://localhost:3000/api/bids/0
Accept: application/json

###
DELETE http://localhost:3000/api/bids/2
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdlcnJhbHRAZW1haWwuY29tIiwiaWQiOjAsInVzZXJuYW1lIjoiZ2VycmFsdCIsInJvbGVzIjpbInVzZXIiLCJhZG1pbiJdLCJpYXQiOjE2MzI2NjA2MDZ9.GUKQJiEHHX3C_abjJj3TSxQxxmU8arPz5iaHokjxd4M
Accept: application/json

###
GET http://localhost:3000/api/bids