###
POST http://localhost:3000/api/credentials
Content-Type: application/json

{
  "username": "gerralt",
  "password": "gerralt123"
}


###
POST http://localhost:3000/api/credentials
Content-Type: application/json

{
  "username": "guus",
  "password": "guus123"
}