### Gerralt
POST http://localhost:3000/api/credentials
Content-Type: application/json

{
  "username": "gerralt",
  "password": "!Gerralt123"
}


### Guus
POST http://localhost:3000/api/credentials
Content-Type: application/json

{
  "username": "guus",
  "password": "!Guus123"
}